export default {
  year1: [
    "he", "she", "we", "me", "be", "you", "all", "are", "her", "was", "they", "my", "the", "a", "do", "to", "today", "of", "said", "says", "were", "was", "is", "his", "has", "you", "your", "they", "be", "he", "me", "she", "no", "go", "so", "by", "my", "here", "there", "where", "love", "come", "some", "one", "once", "ask", "friend", "school", "put", "push", "pull", "full", "house", "our", 'bike', 'time', 'bone', 'note', 'home', 'the', 'that', 'not', 'look', 'and', 'with', 'then', 'could', 'to', 'go', 'will', 'old', 'can', 'little', 'into', 'in', 'back', 'up', 'from'
  ],
  additional: [
    "guarantee", "guardian", "guess", "guest", "guide", "guidebook", "guitar",
    "interpreter", "interrupt", "intermission", "interfere", "international", "antibiotic", "antihero", "antidote"
  ],
  year2: [
    "April", "August", "December", "February", "Friday", "January", "July", "June", "March", "May", "Monday", "Mr", "Mrs", "November", "October", "Saturday", "September", "Sunday", "Thursday", "Tuesday", "Wednesday", "about", "above", "after", "again", "although", "always", "another", "ask", "asked", "baby", "because", "before", "behind", "between", "both", "call", "called", "children", "climb", "could", "different", "eight", "even", "ever", "every", "everyone", "everything", "father", "finally", "five", "four", "friends", "great", "help", "hide", "house", "know", "large", "last", "little", "looked", "love", "many", "most", "mother", "need", "next", "nine", "oh", "once", "only", "other", "our", "over", "people", "please", "really", "school", "seven", "should", "six", "small", "suddenly", "ten", "these", "things", "think", "thorough", "those", "thought", "three", "time", "together", "under", "until", "very", "where", "which", "work", "would", "year", "young"
  ],
  year3: [
    "Christmas", "across", "almost", "along", "animal", "around", "balloon", "beautiful", "began", "being", "below", "better", "birthday", "break", "brother", "brought", "change", "child", "clothes", "cold", "coming", "does", "door", "during", "eyes", "father", "follow", "found", "garden", "goes", "gold", "gone", "grass", "half", "happy", "head", "high", "hour", "important", "improve", "inside", "jumped", "knew", "lady", "leave", "light", "might", "mind", "money", "morning", "move", "much", "near", "never", "number", "opened", "outside", "own", "paper", "parents", "place", "pretty", "prove", "right", "round", "second", "show", "sister", "something", "sometimes", "sound", "started", "still", "stopped", "such", "sugar", "sure", "swimming", "today", "told", "tries", "turn", "upon", "used", "walk", "watch", "water", "while", "white", "whole", "why", "window", "without", "woke", "woken", "word", "world", "write", "year", "yellow"
  ],
  year4: [
    "accident", "accidentally", "actual", "actually", "address", "answer", "appear", "arrive", "believe", "bicycle", "breath", "breathe", "build", "business", "busy", "calendar", "caught", "center", "centered", "century", "certain", "circle", "complete", "consider", "continue", "decide", "describe", "difficult", "disappear", "disbelieve", "early", "earth", "eighth", "enough", "exercise", "experience", "experiment", "extreme", "famous", "favourite", "forward", "forwards", "fruit", "grammar", "group", "guard", "guide", "heard", "heart", "height", "history", "imagine", "increase", "interest", "island", "knowledge", "knowledgeable", "learn", "length", "library", "material", "medicine", "mention", "minute", "natural", "naughty", "notice", "occasion", "occasionally", "often", "opposite", "ordinary", "particular", "peculiar", "perhaps", "popular", "position", "possess", "possession", "possible", "potatoes", "pressure", "probably", "promise", "purpose", "quarter", "question", "rebuild", "recent", "regular", "reign", "remember", "remember", "reposition", "sentence", "separate", "special", "straight", "strange", "strength", "suppose", "surprise", "therefore", "therefore", "though", "through", "various", "weight", "woman", "women", "words"
  ],
  year3_4: [
    "accidentally", "actually", "address", "answer", "appear", "arrive", "believe", "bicycle", "breath", "breathe", "build", "busy", "business", "calendar", "caught", "centre", "century", "certain", "circle", "complete", "consider", "continue", "decide", "describe", "different", "difficult", "disappear", "early", "earth", "eight", "eighth", "enough", "exercise", "experience", "experiment", "extreme", "famous", "favourite", "February", "forward", "fruit", "grammar", "group", "guard", "guide", "heard", "heart", "height", "history", "imagine", "increase", "important", "interest", "island", "knowledge", "learn", "length", "library", "material", "medicine", "mention", "minute", "natural", "naughty", "notice", "occasionally", "often", "opposite", "ordinary", "particular", "peculiar", "perhaps", "popular", "position", "possession", "possible", "potatoes", "pressure", "probably", "promise", "purpose", "quarter", "question", "recent", "regular", "reign", "remember", "sentence", "separate", "special", "straight", "strange", "strength", "suppose", "surprise", "therefore", "though", "although", "thought", "through", "various", "weight", "woman", "women"
  ],
  year5_6: [
    "accommodate", "accompany", "according", "achieve", "aggressive", "amateur", "ancient", "apporent", "appreciate", "attached", "available", "average", "awkward", "bargain", "bruise", "category", "cemetery", "committee", "communicate", "community", "competition", "conscience", "conscious", "controversy", "convenience", "correspond", "criticise", "curiosity", "definite", "desperate", "determined", "develop", "dictionary", "disastrous", "embarrass", "environment", "equipment", "especially", "exaggerate", "excellent", "existence", "explanation", "familiar", "foreign", "forty", "frequently", "government", "guarantee", "harass", "hindrance", "identity", "immediately", "individual", "interfere", "interrupt", "language", "leisure", "lightning", "marvellous", "mischievous", "muscle", "necessary", "neighbour", "nuisance", "occupy", "occur", "opportunity", "parliament", "persuade", "physical", "prejudice", "privilege", "profession", "programme", "pronunciation", "queue", "recognise", "recommend", "relevant", "restaurant", "rhyme", "rhythm", "sacrifice", "secretary", "shoulder", "signature", "sincerely", "soldier", "stomach", "sufficient", "suggest", "symbol", "system", "temperature", "thorough", "twelfth", "variety", "vegetable", "vehicle", "yacht"
  ]
};
