export default {
  additional: [
    "guitar", "guide", "guidebook", "guardian", "guess", "guest", "guarantee"
  ],
  year2: [
    "about", "above", "after", "again", "although", "always", "another", "ask", "asked", "baby", "because", "before", "behind", "between", "both", "call", "called", "children", "climb", "could", "different", "even", "ever", "every", "everyone", "everything", "father", "finally", "friends", "great", "help", "hide", "house", "know", "large", "last", "little", "looked", "love", "many", "most", "mother", "Mr", "Mrs", "need", "next", "oh", "once", "only", "other", "our", "over", "people", "please", "really", "school", "should", "small", "suddenly", "these", "things", "think", "those", "thought", "thorough", "time", "together", "under", "until", "very", "where", "which", "work", "would", "year", "young", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"
  ],
  year3: [
    "across", "almost", "along", "animal", "around", "balloon", "beautiful", "began", "being", "below", "better", "birthday", "break", "brother", "brought", "change", "child", "Christmas", "clothes", "cold", "coming", "does", "door", "during", "eyes", "father", "follow", "found", "garden", "goes", "gold", "gone", "grass", "half", "happy", "head", "high", "hour", "important", "improve", "inside", "jumped", "knew", "lady", "leave", "light", "might", "mind", "money", "morning", "move", "much", "near", "never", "number", "opened", "outside", "own", "paper", "parents", "place", "pretty", "prove", "right", "round", "second", "show", "sister", "something", "sometimes", "sound", "started", "still", "stopped", "such", "sugar", "sure", "swimming", "today", "told", "tries", "turn", "upon", "used", "walk", "watch", "water", "while", "white", "whole", "why", "window", "without", "woke", "woken", "word", "world", "write", "year", "yellow"
  ],
  year4: [
    "accidentally", "actually", "occasionally", "probably", "knowledge", "knowledgeable", "words", "mention", "occasion", "position", "possession", "question", "possess", "caught", "naughty", "eighth", "reign", "weight", "height", "therefore", "famous", "various", "possible", "enough", "bicycle", "business", "disappear", "disbelieve", "rebuild", "reposition", "favourite", "interest", "library", "ordinary", "separate", "address", "appear", "arrive", "difficult", "opposite", "pressure", "suppose", "decide", "describe", "extreme", "guide", "surprise", "earth", "fruit", "heart", "history", "increase", "minute", "natural", "quarter", "regular", "material", "experiment", "length", "center", "century", "certain", "circle", "exercise", "experience", "medicine", "notice", "recent", "answer", "breath", "breathe", "build", "calendar", "complete", "consider", "continue", "early", "group", "guard", "forwards", "heard", "imagine", "island", "learn", "often", "particular", "peculiar", "perhaps", "popular", "potatoes", "promise", "purpose", "remember", "centered", "straight", "strange", "strength", "woman", "women"
  ]
};
